name: Build IW7-Mod

on:
  workflow_dispatch # I think we'll stick to this for the foreseeable future
  # push:
  #   branches:
  #     - main
    # tags: 
    #   - "*" # Trigger the workflow when any tag is pushed. This causes an infinite loop with my janky curl method
  # schedule:
    # - cron: "0 0 * * 0"  # Runs weekly on Sunday at midnight UTC
    # - cron: "*/1 * * * *"  # Runs every 1 minute
    # - cron: "0 0 0 0 0"
jobs:
  build:
    name: Compile Binaries
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Release
    steps:
      - name: Check out files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          # NOTE - If LFS ever starts getting used during builds, switch this to true!
          lfs: false

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Generate project files
        run: tools/premake5 vs2022

      - name: Set up problem matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build release binary
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw7-mod.sln

      - name: Compile installer
        run: |
          ./installer/compile.bat

      - name: Stage release
        run: |
          mkdir staging
          mv data/cdata staging/iw7-mod
          mv "cfg/!start_client.bat" staging/.
          mv cfg/dvars.json staging/iw7-mod/.
          mv build/bin/x64/${{matrix.configuration}}/iw7-mod.exe staging/.
          mv build/bin/x64/${{matrix.configuration}}/tlsdll.dll staging/.

      - name: Create Release Artifacts Dir
        run: |
          mkdir ./release-artifacts

      - name: Upload IW7-Mod installer
        uses: actions/upload-artifact@v3
        with:
          name: iw7-installer
          compression-level: 9
          path: |
            installer/build/iw7-installer.exe

      - name: Upload IW7-Mod zip
        uses: actions/upload-artifact@v3
        with:
          name: iw7-mod
          compression-level: 9
          path: |
            staging/*

      - name: Upload server configuration files
        uses: actions/upload-artifact@v3
        with:
          name: IW7DedicatedConfigs
          compression-level: 9
          path: |
            cfg/*

      - name: Upload standalone release binary
        uses: actions/upload-artifact@v3
        with:
          name: iw7-mod-${{matrix.configuration}}-standalone
          compression-level: 9
          path: |
            staging/iw7-mod.exe

      - name: Upload release debug binary
        uses: actions/upload-artifact@v3
        with:
          name: iw7-mod-${{matrix.configuration}}-debug-binary
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.pdb

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download IW7-Mod ZIP
        uses: actions/download-artifact@v3
        with:
          name: iw7-mod
          path: ./release-artifacts/iw7-mod

      - name: Download IW7-Mod installer
        uses: actions/download-artifact@v3
        with:
          name: iw7-installer
          path: ./release-artifacts

      - name: Download IW7-Mod pdb
        uses: actions/download-artifact@v3
        with:
          name: iw7-mod-Release-debug-binary
          path: ./release-artifacts

      - name: Download IW7DedicatedConfigs
        uses: actions/download-artifact@v3
        with:
          name: IW7DedicatedConfigs
          path: ./release-artifacts/IW7DedicatedConfigs
      
      # - uses: robinraju/release-downloader@v1
      #   with:
      #     repository: 'Rim/iw7-mod'
      #     tag: 'latest'
      #     fileName: 'patch.7z'

      - name: List downloaded files
        run: |
          Get-ChildItem -Path ./release-artifacts -Recurse

      - name: Create zip file from directory
        run: |
          powershell -Command 'Compress-Archive -Path ./release-artifacts/iw7-mod/* -DestinationPath ./release-artifacts/iw7-mod.zip -Force'
          powershell -Command 'Compress-Archive -Path ./release-artifacts/IW7DedicatedConfigs/* -DestinationPath ./release-artifacts/IW7DedicatedConfigs.zip -Force'

        # This is the jankiest shit I've ever done, but it works
      - name: Delete Tag
        run: |
          curl -X "DELETE" "https://git.rimmyscorner.com/api/v1/repos/Rim/iw7-mod/tags/latest" -H "authorization: token ${{ secrets.TOKEN }}"

      - name: Delete Release
        run: |
          curl -X "DELETE" "https://git.rimmyscorner.com/api/v1/repos/Rim/iw7-mod/releases/tags/latest" -H "authorization: token ${{ secrets.TOKEN }}"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: latest
          release_name: IW7-Mod
          body: |
            ### Steam Verification has been removed. You do **<u>NOT</u>** need to own the game in order to play.
            - [Where can I get the game?](https://git.rimmyscorner.com/Rim/iw7-mod#where-can-i-get-the-game)
            - [Instructions](https://git.rimmyscorner.com/Rim/iw7-mod#instructions)


            ## Disclaimer<a id="disclaimer"></a>

            We do not condone piracy of any kind. Asking for, providing, or discussing illegal download links is not allowed in our communities.

            <a id="downloads"></a>
          draft: false
          prerelease: false

      # This man shogo82148 really saved my sanity after HOURS of screwing with this using the official unmaintained repo...
      - name: Upload IW7-Mod ZIP to Release
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/iw7-mod.zip
          asset_name: iw7-mod.zip
          asset_content_type: application/octet-stream

      - name: Upload IW7-Mod debug binary
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/iw7-mod.pdb
          asset_name: iw7-mod.pdb
          asset_content_type: application/octet-stream

      - name: Upload IW7 Installer to Release
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/iw7-installer.exe
          asset_name: iw7-installer.exe
          asset_content_type: application/octet-stream

      - name: Upload IW7 Dedicated Configs
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/IW7DedicatedConfigs.zip
          asset_name: IW7DedicatedConfigs.zip
          asset_content_type: application/octet-stream
